[workspace]
members = [
    "crates/securerx-core",
    "crates/securerx-node",
    "crates/securerx-api",
    "crates/securerx-cli",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

