global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nodes'
    static_configs:
      - targets: ['node1:9090','node2:9090','node3:9090']
    metrics_path: /metrics

  - job_name: 'api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: /metrics

rule_files:
  - "/etc/prometheus/rules/rules.yml"
